### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by bakmei** [jfree/jfree-demos#1]
The dependency version for org.jfree.chart3d needs to be updated.

**Comment by greatm84** [comment]
need to modify chart3d dependency version at  'pom.xml'


        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>org.jfree.chart3d</artifactId>
            <version>2.1.0</version>
        </dependency>

**Comment by jfree** [comment]
A bit late but...fixed.

**Comment by jfree** [comment]
Thanks for the report.
